platformio/platformio-core

platformio/util.py

I would like to propose an improvement to the handling of lib_dir. I'm using platformio for an Arduino project and I try to keep the original directory structure as intended by the Arduino IDE. In that way, nobody is forced to use platformio, because Arduino IDE can be used to compile the project, too. I've already used the trick, described in https://github.com/ivankravets/platformio/issues/41 and renamed my main ino file to src.ino. It's a hack, but it works.
Now, there is only one thing left: The library path for the project has to be modified. It is one directory up in the path hierarchy. As the project is checked in to a version control system and platformio should work out of the box without adjusting any properties, I need to be able to set a relative directory path, and not an …

Fixing handling of relative library paths

---

platformio/boards/adafruit.json
platformio/boards/arduino.json
platformio/boards/digistump.json
platformio/boards/engduino.json
platformio/boards/microduino.json
platformio/boards/misc.json
platformio/builder/scripts/atmelavr.py
platformio/builder/scripts/atmelsam.py

2. Add second upload method through native USB Port for SAM-based boards
3. Add SainSmart Due board

Add "require_upload_port" board option // Resolve #107

---

platformio/boards/adafruit.json
platformio/boards/arduino.json
platformio/boards/digistump.json
platformio/boards/misc.json
platformio/boards/nordicnrf51.json
platformio/boards/nxplpc.json
platformio/boards/sparkfun.json
platformio/boards/ststm32.json
platformio/boards/timsp430.json
platformio/boards/titiva.json
platformio/builder/main.py
platformio/builder/scripts/frameworks/arduino.py

* Add support for SparkFun boards // Resolve #127
* Normalize board names // Resolve #128
* Add support for Sanguino boards // Resolve #131
* Allow own libs per framework's core // Resolve #133

Allow own libs per framework's core; Add support for Sanguino, SparkFun boards

---

platformio/exception.py

`$ platformio install [platform]`
The above line is obsolete, I've changed the recommendation to reflect this latest version of the program:
`$ platformio platforms install [platform]`

Updated recommened platforms install command

---

platformio/builder/tools/pioupload.py

Fixed a grammatical mistake, made the meaning  of the error clearer by replacing "it" with "this" and by adding an example.
It does increase the length of the output, but I think it's much easier to read and more informative.

improved error wording

---

docs/ide/emacs.rst

Just noticed a small typo on one of the key bindings.

Fix typo in Emacs documentation

---

examples/mbed/mbed-http-client/src/main.cpp

The URL for the file used in the mbed HTTP Client example has changed from http://mbed.org/media/uploads/donatien/hello.txt to https://developer.mbed.org/media/uploads/donatien/hello.txt

updated URL in example to new mbed domain

---

docs/ide/emacs.rst
platformio/ide/tpls/emacs/CMakeLists.txt.tpl

As per #427.
Added in the remaining targets to my `CMakeLists.txt` file and updated the docs with the new key bindings.
I've already pushed the corresponding changes to the Emacs package: ZachMassia/@69d584003332908f49f25fb614ed67925a23a578

Add external programmer and SPIFFS targets to Emacs

---

docs/ide/emacs.rst

Just noticed I forgot to remove the reference to CMake in the doc page.
Also reworded a sentence.
Thanks

Update Emacs doc page

---

platformio/builder/tools/piomisc.py
tests/ino2cpp/basic/basic.ino
tests/test_ino2cpp.py

The InoToCPPConverter class does not match templated methods, like for instance this one:
```
template<typename T> bool setSetting(const String& key, T value) {
return Embedis::set(key, String(value));
}
```

Added support for templated methods in InoToCPPConverter

---

platformio/ide/tpls/clion/CMakeListsPrivate.txt.tpl

The same fix as in commit 7354515 by @ivankravets, plus:
* correct handling of macro-functions with concatenation (`##`) operation
* correct behaviour for spaces in macros. Without quotes around `-D` option's argument I experienced errors like:
```
Problems were encountered while collecting compiler information:
xtensa-lx106-elf-g++: error: long: No such file or directory
xtensa-lx106-elf-g++: error: unsigned: No such file or directory
xtensa-lx106-elf-g++: error: int: No such file or directory
```
for defines like `add_definitions(-D__UINT_LEAST64_TYPE__=long long unsigned int)`
"idea" of `-D...` -> `-D'...'` taken form [here](https://gcc.gnu.org/onlinedocs/cpp/Invocation.html).
This patch:
* Tested on CLion 2017.2.3: IDE imports project without warnings or errors
* Verified correct …

Additional fix to 7354515

---

platformio/ide/projectgenerator.py
platformio/ide/tpls/clion/CMakeListsPrivate.txt.tpl

This PR fixes the problem discussed in [this post](https://community.platformio.org/t/clion-fails-to-find-include-files-in-lib-folder/3247) by adding source files from `lib` and `.piolibdeps` to `SRC_LIST`.

Fix CLion not recognizing includes in lib and .piolibdeps

---

platformio/ide/tpls/vim/.clang_complete.tpl
platformio/ide/tpls/vim/.gcc-flags.json.tpl

When a library has whitespaces in the name the path
will contain whitespace too. When vim tries to decode
path it will fail.
This fix wrap each path with quotes.

Solved issues with vim whitespaces in paths

---

scripts/99-platformio-udev.rules

Fixes `[Errno 16] Device or resource busy: '/dev/ttyACM0` issue on Teensy 3.2 and 3.5 (at minimum) due to ModemManager probing the devices and making them unavailable. Updated rules sourced from current https://www.pjrc.com/teensy/49-teensy.rules configuration.
Came across the issue due to this forum post: https://community.platformio.org/t/platformio-difficult-to-configure/8189/2

Fix Teensy serial lockout

---

platformio/ide/tpls/vscode/.gitignore.tpl

One of the recent updates to the vscode-cpptools extension made it start caching in .vscode/ipch, and this cache can be quite big for even small projects. Since they're cache files, they should be ignored by default. This may be a short-lived suggestion, as there is already some mention that the IntelliSense cache folder may be moved to workspace storage, rather than 'per project' storage... although the 'when' is anyone's guess. 
See here for more: https://github.com/microsoft/vscode-cpptools/issues/3347

Ignore vscode-cpptools cache

---

scripts/get-platformio.py

Shouldn't have been able to break this the way I did... but I did (by-product of trying to coerce an embedded python install to work with platformio on windows). python3 hurdles. 
```
File "get-platformio.py", line 93
print r['out']
^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(r['out'])?
```
and 
```
File "get-platformio.py", line 146
except Exception, e:
^
SyntaxError: invalid syntax
```

Missing parentheses and depreciated syntax

---

platformio/ide/tpls/eclipse/.cproject.tpl

In the current version of this template, all build targets result in a command line
pio -c -f eclipse debug run target <mytarget>
The commit fixes this to be
pio -c -f eclipse run target <mytarget>
See also discussion in forum:
https://community.platformio.org/t/pio-4-0-0b3-potential-bug-in-cprojet-tpl/8390

Fix for tpls/eclipse/.cproject.tpl

---

platformio/ide/tpls/clion/.idea/workspace.xml.tpl
platformio/ide/tpls/clion/CMakeLists.txt.tpl
platformio/ide/tpls/clion/CMakeListsPrivate.txt.tpl

Better CLion integration using the new access to ProjectConfig from ProjectGenerator ( 1dc15326c9d5d3e894e20d5ed2dfc89d4c9358e1 ).
Thanks to the changes this was much cleaner and faster to do. I would have preferred not to use `load_project_ide_data()` to get the full list of includes and defines but I could not figure how to do it easily just with `config`.
Currently the build profile allowing to run every environment (previous behaviour) is the last on the list, would you prefer it to be the default  ?

Clion integration, resolves #2824

---

scripts/99-platformio-udev.rules

On boards like the Arduino Micro, when in bootloader mode it appears ModemManager interferes with the programming process and result in a catastrophic failure with no end of different errors including, but not limited to:
```
error: programmer did not respond to command: write block
error: butterfly programmer uses avr_write_page() but does not provide a cmd() method.
error: programmer did not respond to command: set addr
```
After this, the device could appear to be completely non-functional, refusing to enumerate or appear for programming, but thankfully a double-reset will usually recover it, but the underlying ModemManager issue will still prevent successful programming. Hence the additional rules. 
This affects not only PlatformIO, but also the Arduino IDE (on linux). 
For my device, …

Stop ModemManager corrupting Arduino uploads

---

platformio/commands/test/embedded.py

Some boards, like ESP32 based boards, give some unintelligible data when connecting to them via Serial. This is sometimes data that is send with the wrong baud rate (hard baked into the boot loader), or something else. It's hard to prevent this from happening. When a build is uploaded to the ESP board for unit testing, the decoding of the incoming stream should not fail the test due to some garbled content. Since the read data is validated on line 95, any garbage is automatically ignored and only outputted to the console.

UTF8 decoding should ignore invalid characters coming from the serial connection

---

scripts/99-platformio-udev.rules

Used for example on [Sipeed Logan Nano](https://docs.platformio.org/page/boards/gd32v/sipeed-longan-nano.html)

udev: Add GD32V DFU Bootloader

---

scripts/get-platformio.py

Fixes:
```
'dict' object has no attribute 'iteritems'
[FAILURE]
```
and
```
name 'basestring' is not defined
```
when run with Python3.5+ on Windows

Replace deprecated in python3: iteritems with items and basestr with str

---

platformio/builder/tools/piomisc.py
platformio/project/options.py
tests/test_builder.py

This will allow users to override default debug flags for example in cases when the final binary built in debug mode is too large to be loaded on target (e.g. https://github.com/platformio/platform-ststm32/issues/341)

Add new debug_build_flags option

---

HISTORY.rst
platformio/builder/tools/pioide.py
platformio/ide/tpls/atom/.gcc-flags.json.tpl
platformio/ide/tpls/clion/CMakeListsPrivate.txt.tpl
platformio/ide/tpls/vscode/.vscode/c_cpp_properties.json.tpl

This PR resolves cases when a compiler flag contains a path with spaces as argument (e.g. `-iprefix`, `-imacros`, etc). These flags are crucial for some IDEs to provide a better code completion experience (e.g. #3364).

Update templates for Atom, VSCode, CLion

---

platformio/commands/device.py
platformio/compat.py

TODO:
This PR has been split into three parts, this one implements an interface to add more filters into miniterm and more in in platform repos, adding filters to decode the traces:
* https://github.com/platformio/platform-espressif32/pull/286
* https://github.com/platformio/platform-espressif8266/pull/197
**Original text below:**
I've implemented automatic ESP crash trace decoding in the device monitor in platform.io. It is  using a miniterm filter, add `--filter=esp_exception_decoder` to `monitor_flags` to use it.
It looks like this with a debug build (the indented part is new): ![Screenshot_20200215_190846](https://user-images.githubusercontent.com/120108/74592997-39aff180-5027-11ea-998a-1b2ce128fef2.png)
This is pretty much just a proof of concept, I've got some questions:
1. It's …

Add ESP crash trace decoding to monitor

---

platformio/builder/tools/compilation_db.py

By placing the `where_is_program` call into this function, all references to the compiler will be made absolute, instead of just ones in the top environment. For example, previously all references to the compiler for user source code would not use the full path in the compilation database, which broke `clangd`'s detection of system includes.

Ensure all commands in compilation_commands.json use absolute paths.

---

platformio/commands/test/processor.py

C file should be used by default as only Arduino and mbed require C++ files.
There might be a lot of legacy projects so custom transport is also set to use C++.

Dynamically choose extension for file with unit test transport

---

HISTORY.rst
platformio/builder/tools/pioide.py
platformio/ide/projectgenerator.py
platformio/ide/tpls/atom/.clang_complete.tpl
platformio/ide/tpls/atom/.gcc-flags.json.tpl
platformio/ide/tpls/clion/CMakeListsPrivate.txt.tpl
platformio/ide/tpls/codeblocks/platformio.cbp.tpl
platformio/ide/tpls/eclipse/.cproject.tpl
platformio/ide/tpls/emacs/.ccls.tpl
platformio/ide/tpls/emacs/.clang_complete.tpl
platformio/ide/tpls/netbeans/nbproject/configurations.xml.tpl
platformio/ide/tpls/qtcreator/platformio.pro.tpl
platformio/ide/tpls/vim/.ccls.tpl
platformio/ide/tpls/vim/.clang_complete.tpl
platformio/ide/tpls/vim/.gcc-flags.json.tpl
platformio/ide/tpls/visualstudio/platformio.vcxproj.tpl
platformio/ide/tpls/vscode/.vscode/c_cpp_properties.json.tpl

Should fix #3460. Besides, global folders in `SRC_LIST` paired with `GLOB_RECURSE` seem a bit unnecessary since there might be unused libraries in these folders

CLion: Add paths to libraries specified via lib_extra_dirs option

---

platformio/ide/tpls/emacs/.gitignore.tpl
platformio/ide/tpls/vim/.gitignore.tpl

Adds `.ccls` in `.gitignore` for Vim (introduced in 223a85baca14150400e324ae39196be87822e265) and Emacs (introduced in 7a07a2e63eb51f8e403ecaf0fb2e4029d7b54744).
The file `.ccls` doesn't need to be tracked in git as it contains user/machine-related configurations (similar to `.clang_complete`).

Add .ccls to .gitignore (vim and emacs)

---

setup.py

The addition of the `tests/__init__.py` makes `find_packages()` recognize `tests` as additional python package. Now this unexpected module gets also installed by pip, possibly into system site-packages. This could cause conflicts with other packages, so I suggest excluding it again.

Exclude tests from python package setup

---

platformio/ide/tpls/vim/.ccls.tpl

This change fixes quoted strings in defines in the ccls vim template.
```diff
--DARDUINO_BOARD=&quot;PLATFORMIO_D1_MINI&quot;
+-DARDUINO_BOARD="PLATFORMIO_D1_MINI"
```

fix quoting of defines in ccls template

---

scripts/99-platformio-udev.rules

The Atmel AVR Dragon ist not sold anymore, but used to be a much cheaper alternative to a JTAGICE; therefore it's still in use by some people (like me ;-)

Add udev rule for Atmel AVR Dragon

---

platformio/commands/check/tools/pvsstudio.py

I have a problem with PVS-Studio code check when the path to the project contains spaces.
`D:\platformio test>C:\Users\tester\.platformio\penv\Scripts\platformio.exe check -v`
```
Checking miniatmega328 > pvs-studio (platform: atmelavr; board: miniatmega328; framework: arduino)
------------------------------------------------------------------------------------------------------------------------
C:\Users\tester\.platformio\packages\toolchain-atmelavr\bin\avr-g++.exe D:\platformio test\src\main.cpp -E -o C:\Users\tester\AppData\Local\Temp\piocheckksjp2hbh\oxlnipks.i -fno-exceptions -fno-threadsafe-statics -fpermissive -std=gnu++11 -Os -Wall -ffunction-sections -fdata-sections -flto -mmcu=atmega328p -DPLATFORMIO=50100 -DARDUINO_AVR_MINI -DF_CPU=16000000L -DARDUINO_ARCH_AVR -DARDUINO=10808 …
```

A fix for compiler invocation from the PVS-Studio code check

---

setup.py

The [`zeroconf`](https://github.com/jstasiak/python-zeroconf) package has been upgraded to 0.32.0 recently with some bugfixes, nice work on better compliance with RFCs, and asyncio support.
Changelog: https://github.com/jstasiak/python-zeroconf#0320
Tested using: `pio device list --mdns` and quite a few mDNS-enabled devices on the network; no difference before/after upgrade

Bump zeroconf to 0.32

---

HISTORY.rst
platformio/commands/ci.py
tests/commands/test_ci.py

This fixes #4011 and possible "FileExists" errors when the "platformio ci" command by safely copying sources to the build folder

Properly handle "--keep-build-dir" option in platformio ci command

---

HISTORY.rst
platformio/commands/check/tools/cppcheck.py
tests/commands/test_check.py

This PR resolves #3944 by converting possible draft versions of C++ standards set in build flags to regular ISO C++ standards valid in Cppcheck

Properly handle C++ standards when invoking Cppcheck

---

platformio/package/manager/library.py

Extends the list of folder names which PlatformIO detects as root folder in case there is no library manifests by the element "inc". 
Would fix the issue described in https://community.platformio.org/t/wrong-install-by-git-link-of-lib-without-manifest/24228.

Add "inc" as sign that it's the root of the library

---

platformio/project/tpls/clion/CMakeListsPrivate.txt.tpl

This fix adds spaces to the regex substitutions on CMakeListsPrivate.txt add_definitions.
Fixes #4102

Escape spaces in CLion CMakeListsPrivate template - FIXES #4102

---

platformio/clients/http.py

Hello!
Thank you for this great project!
I use IPv6-only workstation with Gentoo GNU/Linux. To connect to IPv4-only resources, I use public services NAT64 + DNS64.
All the software works fine, except PlatformIO:
```
% pio update --dry-run
Platform Manager
================
Platform gd32v
--------
Checking platformio/gd32v                     1.2.1                              [Off-line]
Checking platformio/framework-gd32vf103-sdk   1.0.0 @ ~1.0.0                     [Off-line]
Checking platformio/tool-openocd-gd32v        0.1.1 @ ~0.1.1                     [Off-line]
Checking platformio/tool-gd32vflash           0.1.0 @ ~0.1.0                     [Off-line]
Checking platformio/toolchain-gd32v           9.2.0 @ ~9.2.0                     [Off-line]
Checking platformio/tool-dfuutil …
```

_internet_on: try IPv4, if not acceptable — try IPv6

---

HISTORY.rst
platformio/project/helpers.py

On linux, "Documents" doesn't have to be the right folder. It depends on the language selected when installing the operating system.
This PR addresses #4156

Fixed wrong path

---

scripts/99-platformio-udev.rules

Added udev rule for FireBeetle-ESP32.

---

CONTRIBUTING.md
HISTORY.rst
README.rst

It's just a little change, but at the some lists there is a dot at the last point, that is inconsistent.
The dot at the README.rst:
```diff
- * Firmware File Explorer and Memory Inspection.
+ * Firmware File Explorer and Memory Inspection
``` 
There is also an inconsistent dot at HISTORY.rst:
```diff
-  - Drop support for Python 2 and 3.5.
+  - Drop support for Python 2 and 3.5
```
The same for CONTRIBUTING.md:
```diff
- 1. Fork the repository on GitHub.
+ 1. Fork the repository on GitHub
- 11. Submit a Pull Request on GitHub.
+ 11. Submit a Pull Request on GitHub
```

Removing inconsistent dot at README.rst, HISTORY.rst and CONTRIBUTING.md

---

platformio/commands/check/tools/clangtidy.py

Fixes #4186
Appending --checks=* causes clang-tidy to ignore the flags --config and --config-file from `check_flags`, which breaks the ability to use a clang-tidy file.

Don't append --checks=* when the --config or --config-file flags are set

---

platformio/package/manager/_update.py
platformio/package/vcsclient.py

b/c we can't use `pull` anyway in that situation
also ask *only* for the specific branch via `refs/heads/{branch}` and fail when it is not available. `pkg update` / `pkg outdated` will not do or display anything if that's the case.
resolves #4139 
(and I am not familiar with the svn & hg cases, so only git implementation was changed)

Avoid working with detached / non-existent git branches when checking for updates

---

.github/workflows/projects.yml

This PR adds a new CI workflow that should catch basic regressions to safeguard the most popular projects that rely on PlatformIO. The following projects are checked:
- [MarlinFirmware/Marlin](https://github.com/MarlinFirmware/Marlin)
- [esphome/esphome](https://github.com/esphome/esphome)
- [scottbez1/smartknob](https://github.com/scottbez1/smartknob)
- [xoseperez/espurna](https://github.com/xoseperez/espurna)
- [1technophile/OpenMQTTGateway](https://github.com/1technophile/OpenMQTTGateway)
Note that the CI will be run only on PUSH events in the `release/*` and `project*` branches.

Add CI workflow for popular PlatformIO projects

---

platformio/commands/remote/client/agent_service.py

filter argument is being sent to remote agent, but is not being used.
This will fix these kind of commands:
```
platformio remote test -e xx -f test_xx
```
related issue #4204

Fix filter argument used in remote agent

---

platformio/test/helpers.py
platformio/util.py
tests/project/test_savedeps.py

There are small typos in:
- platformio/test/helpers.py
- platformio/util.py
- tests/project/test_savedeps.py
Fixes:
- Should read `specified` rather than `sepcified`.
- Should read `overridden` rather than `overriden`.
- Should read `compatibility` rather than `compatiblty`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md

docs: Fix a few typos

---

platformio/builder/tools/piolib.py

In some situation when using 'native' platform then pio might treat some libraries as compatible even if lib_compat_mode=strict is used and it will then fail to compile arduino library under native platform.
As native does not contain any 'framework' then 'is_frameworks_compatible()' might treat library as compatible even if library.json says its for 'arduino' only for example
Untill now i used lib_ignore to overcome this issue but in long term its hassle to keep it updated
```
platformio.ini
[env:main_dev_SDL]
platform = native
; framework = none
; board = non
lib_compat_mode = strict ; do nothing in this case as is_frameworks_compatible() will be false positive when no framework defined
[env:main_dev]
platform = espressif32
framework = arduino
board = esp32dev
```
```
library.json
{ …
```

fix compat mode when no framework

---

platformio/builder/tools/piobuild.py

It appears `env` is not yet fully when the pre-script is ran (env vs projenv?), however when Build Middlewares are employed [as described](https://docs.platformio.org/en/stable//scripting/middlewares.html), this incomplete environment is used to construct the env.Object entries, leading to missing compiler arguments.
Similar problems are mentioned [here](https://community.platformio.org/t/addbuildmiddleware-missing-include-flags-i/23594)
This PR optionally, as to not break compatibility, passes the _current_ environment  to the callback, in-line with how its handled with [Pre & Post action callbacks](https://docs.platformio.org/en/stable//scripting/actions.html)
To reproduce the issue:
```python
def rewrite_source(node):
return env.Object(node)
env.AddBuildMiddleware(rewrite_source)
``` …

optionally pass env to AddBuildMiddleware callback

---

platformio/system/completion.py

the output of `bash --version` is different when the system is configured for e.g. de_DE locale. For german locale the it's `GNU bash, Version 5.0…` with an uppercase 'V'. This makes the bash completion setup fail with the error `Error: The minimal supported Bash version is 4.4`.
To fix this, the version match regex now uses the `IGNORECASE` flag.

make bash version check case insensitive

---

scripts/99-platformio-udev.rules

For me at least those entries are necessary. Even after adding my user to the relevant groups it refused to connect to the device.

Add udev Entry for Wio Terminal

---

platformio/public.py

This would help platform developers ensure compatibility between versions. 
In short, I ran for hours after a changed import. 
I think this commit introduced this issue: https://github.com/platformio/platformio-core/commit/a6e61a7a5a24cf73d2866b9817e8b9a7e99852d0
This would save others from that: https://github.com/maxgerhardt/platform-raspberrypi/issues/15

Add list_logical_devices to public

---

platformio/assets/system/99-platformio-udev.rules

It's a low cost dev board that can use as DAPLink debugger. [info](https://wiki.luatos.com/chips/air32f103/board.html)  
This PR fixed `Error: unable to open CMSIS-DAP device 0xd28:0x204` while running upload task.

add udev rule for AIR32F103 board

---

HISTORY.rst
platformio/check/cli.py
platformio/check/tools/base.py
platformio/check/tools/clangtidy.py
platformio/check/tools/cppcheck.py
platformio/check/tools/pvsstudio.py
platformio/project/options.py
tests/commands/test_check.py

This PR introduces refactored functionality for source files filtering via templates, for example:
```ini
[env:check_src_filter]
platform = ...
board = ...
check_src_filters =
-<src/*>
+<src/spi/spi.cpp>
-<tests/>
+<tests/test_embedded/*.c*>
```
Resolves #4566

Improved file filtering for the Static Analysis feature

---

platformio/builder/tools/pioino.py

Noticed while building .ino files at esp8266 repo
https://github.com/esp8266/Arduino/actions/runs/4578253831/jobs/8084637114?pr=8901#step:5:174
```
/tmp/tmpo60cxu_1/src/onewiretest.ino: In function 'void loop()':
/tmp/tmpo60cxu_1/src/onewiretest.ino:31:2: error: 'checkSwSerial' was not declared in this scope
31 |  checkSwSerial(&swSer1);
|  ^~~~~~~~~~~~~
*** [.pio/build/nodemcuv2/src/onewiretest.ino.cpp.o] Error 1
```
Where the signature should be
```
void checkSwSerial(EspSoftwareSerial::UART*);
```
Locally, to reproduce
```
> git clone https://github.com/plerup/espsoftwareserial/
> pushd espsoftwareserial/examples/onewiretest
> pio ci -b esp32dev -l "$PWD/../../" ./

InoToCpp: add ':' to arguments regexp

---

platformio/test/runners/unity.py

They appear when the tests are run with the `Wextra` flag.
I know of 3 possible solutions:
* A.) `static_cast<void>(unusedParameter);` – the preferred C++ way, but `unity` can also be used with `C`
* B.) `(void) unusedParameter;` – "old" C–style casting – the one I used – compatible with both C and C++
* C.) remove `unusedParameter` var from the function arguments – but keeping the name better explains what it is
```
Library Manager: Installing throwtheswitch/Unity @ ^2.5.2
Unpacking  [####################################]  100%
Library Manager: Unity@2.5.2 has been installed!
.pio/build/native/unity_config/unity_config.c:39:37: warning: unused parameter 'baudrate' [-Wunused-parameter]
void unityOutputStart(unsigned long baudrate) { }
^
1 warning generated.
Testing...
```

test/runners/unity.py: fixed warnings: `[-Wunused-parameter]`

---

platformio/assets/system/99-platformio-udev.rules

add Espressif USB JTAG/serial debug unit to udev

---

platformio/builder/tools/piobuild.py
platformio/builder/tools/piolib.py

separated out the optional addition of toolchains to compiledb include paths and added a call to it in the library building step for user defined libraries, allowing the automatic inclusion of toolchains in private lib compiledb generation
related to issue #4762

Issue #4762 compiledb include toolchains with user defined libs

---

platformio/proc.py

In verbose mode, output from the build command was constantly being appended to an unused buffer, character by character. Even a simple project using ESP-IDF would generate over 5 million append operations, which is quite slow because the backing memory for this buffer has to be constantly reallocated.
The actual buffer that's used is the local `line` variable. An alternative fix would be to remove `line` and use `self._buffer` instead, so that the `get_buffer()` method will return the buffer contents.
| | Time to compile |
| --- | --- |
| Baseline (non-verbose) | 22.97 seconds |
| Before patch (verbose) | **1722.01 seconds** |
| After patch (verbose) | 24.23 seconds |
Fixes #4783.

Remove unused build output buffer

---

platformio/builder/tools/piomaxlen.py

The maximum length of the string that you can use at the command prompt is 8191 characters.
This limitation applies to:
the command line
individual environment variables that are inherited by other processes, such as the PATH variable all environment variable expansions
If you use Command Prompt to run batch files, this limitation also applies to batch file processing.
https://learn.microsoft.com/en-us/troubleshoot/windows-client/shell-experience/command-line-string-limitation#:~:text=The%20maximum%20length%20of%20the,such%20as%20the%20PATH%20variable

Update piomaxlen.py change from 8192 to 8191 MAX_LINE_LENGTH

---

platformio/assets/system/99-platformio-udev.rules

In case of interfacing an STM32 chip as USB-CDC device. This enabled me to treat the USB-port of the Electrosmith Daisy Seed as a normal `/dev/ttyACMx` serial interface. Other use-cases are not known to me, you guys decide if that is a worthy addition.

Add STM32 virtual COM port to `udev.rules`

---

platformio/package/manager/base.py

While developing a library package, I tried to use a `symlink://` specification in my test application to point to my library's development checkout.  Unfortunately this seemed to cause a number of issues:
- The symlinked package did not appear in `platformio pkg list`
- Every build would "re-install" the symlink package
- As a result of the "reinstallation", the PlatformIO VSCode plugin would try to re-configure itself mid-build, causing a number of failures as it deleted some of the working build folders
I traced this to the installed symlink package not matching its own pkg spec in `package/manager/base.py`.   It looks like it just needed the same `abspath()` check as a `file://` specification.

Fix symlink package spec validation

---

platformio/check/cli.py
tests/commands/test_check.py

My src_dir and include_dir are not in the same directory as the platformio.ini, which prevented the check tool from working.
I found out why, and this is my fix!

paths fix for check tool

---

platformio/assets/system/99-platformio-udev.rules

As Zephyr is officially supported by platformio, it make sense to add its default VID:PID to udev rules.
This will also encompass support for MCUBOOT using zephyr in USB serial mode.

Adding Zephyr framework USB VID PID to udev rules.

---

platformio/dependencies.py

I need to loosen the dependency bound for the package in the development (Rawhide/F41) and latest stable (F40) versions of Fedora Linux, so I’m offering the change as a PR.
https://github.com/encode/starlette/releases/tag/0.38.0
-----
- Allow use of `memoryview` in `StreamingResponse` and `Response`
- Send 404 instead of 500 when filename requested is too long on `StaticFiles`
- Fail fast on invalid `Jinja2Template` instantiation parameters
- Check endpoint handler is async only once
- Add proper synchronization to `WebSocketTestSession`
-----
I tested this with `tox -e testcore` and did not observe any regressions.

Allow Starlette 0.38.1

---

platformio/util.py

adds a check for `PLATFORMIO_SYSTEM_TYPE` environment variable in the system type detection, so that the system type may be defined manually by the user.
this should help in cases where the detection fails, e.g. on windows on arm64 systems that support x86 emulation. 
in those cases, it'd be ok for platformio to pretend like the system is `windows_x86`, since x86 binaries are executed through emulation.
see https://community.platformio.org/t/windows-on-arm64-problem-installing-xtensa-toolchain/25497 for more details.

allow manual override of system type

---

platformio/dependencies.py

This release of Starlette contains a fix for a security bug:
- GHSA-f96h-pmfr-66vw: https://github.com/encode/starlette/security/advisories/GHSA-f96h-pmfr-66vw
- CVE-2024-47874: https://nvd.nist.gov/vuln/detail/CVE-2024-47874
I tested this with `tox -e testcore` and did not observe any regressions.

Allow Starlette 0.40.x

---

platformio/package/download.py

Fixes downloading library dependencies from Azure Devops repositories.
See https://community.platformio.org/t/error-downloading-installing-git-repositories-from-behind-a-firewall/9524/2?u=maxgerhardt

Allow HTTP 203 as successful response

---

platformio/package/meta.py
platformio/package/unpack.py

currently `zip` and `tar.gz` as compressed source for packages are supported.
This PR adds support for `tar.xz` compressed tarballs.

add support for `tar.xz` tarballs

---

platformio/project/commands/init.py

I changed some of the markdown (no code) in platformio/project/commands/init.py to be more clear and fix a couple grammar issues.
Noticed them while reading a README it generates and figured I could polish it up!

Clarified language and fixed some grammar issues
