tests/commands/test_lib.py
tests/test_pkgmanifest.py

And cover "lib" commands with tests

Cover package manifest with tests // Issue #69

---

platformio/boards/digistump.json
platformio/builder/scripts/atmelsam.py
platformio/builder/scripts/digistump.py
platformio/platforms/digistump.py

2. Update atmelsam uploader options

Update digistump uploader

---

examples/mbed/mbed-serial/README.rst
examples/mbed/mbed-serial/platformio.ini
examples/mbed/mbed-serial/src/main.cpp
platformio/builder/scripts/frameworks/mbed.py

Add serial port example with mbed framework

Fix mbed framework // Resolve #122

---

docs/platforms/creating_platform.rst
platformio/builder/main.py
scripts/docspregen.py

* Assert error when board's platform mismatch

Automatically generate "Packages" block for "Creating platform" page // Resolve #139

---

platformio/builder/scripts/teensy.py

I added the soft reboot switch to the teensy_loader_cli, so that you don't have to press the reset button on the Teensy each time.

added soft reboot to teensy_loader_cli

---

README.rst

Some minor edits that I think makes it a little easier to read.

Slight grammar/wording tweaks

---

examples/stm32/stm32-cmsis-blink/src/main.c
examples/stm32/stm32-spl-blink/platformio.ini
platformio/boards/ststm32.json
platformio/builder/scripts/frameworks/cmsis.py
platformio/builder/scripts/frameworks/libopencm3.py
platformio/builder/scripts/frameworks/spl.py

Update builders for CMSIS, SPL, libopenCM3

Add CMSIS support for nucleo_f401re board  // Resolve #373

---

docs/projectconf.rst

I couldn't find information on how to overclock my teensy with platformio until I asked in the chat and @ivankravets pointed me to this page. Mentioning overclocking should help others find that information more easily.

Mention "overclocking"

---

README.rst
docs/librarymanager/creating.rst

I just recently played with the library manager for the first time. With regards to registering your own library and from a perspective of a first time user, i thought these additions to docs/librarymanager/creating.rst would have been good to have in the documentation.

Doc updates

---

README.rst

make data collection transparent

add telemetry / privacy policy reference

---

scripts/99-platformio-udev.rules

Signed-off-by: Yusuf Soyipek's ysoyipek@iora.com.tr

Add FT231XS ids for Sparkfun ESP32 Thing

---

MANIFEST.in

@ivankravets since you only ship source dists, I think this is enough.
If you were to ship wheels (even universal wheels) you would have to do it through `setup.cfg`.

Add license file to sdist using MANIFEST.in

---

HISTORY.rst
platformio/exception.py
platformio/maintenance.py

Use consistently the same host and url and fix one unmatched anchor.

Fix link to FAQ sections

---

HISTORY.rst
platformio/ide/tpls/vscode/.vscode/launch.json.tpl

This should fix the issue #3824

Preserve user-specified debug configurations in VSCode integration

---

HISTORY.rst
platformio/builder/tools/platformio.py

Explicitly specify PROGSUFFIX when compiling final binary

---

platformio/project/config.py

Fix charmap error on cyrilic in platformio.ini file #3493

Fix charmap error

---

platformio/commands/remote/command.py

Propagate agent option to remote device monitor command

---

README.rst

#StandWithUkraine

---

platformio/commands/remote/command.py

Adding --filter option to remote test
Related with #4204

Add --filter to remote test

---

platformio/project/tpls/qtcreator/.gitignore.tpl
platformio/project/tpls/qtcreator/platformio.files.tpl

* add .gitignore to project files
* exclude .qtc_clangd/
* don't exclude user project config file

qtcreator IDE gitignore tweaks

---

platformio/assets/schema/library.json

This is first draft of the schema, descriptions are taken from the documentation. 
I've verified its working with vscode.

add library.json schema

---

platformio/builder/tools/pioino.py

Reverts platformio/platformio-core#4586

Revert "InoToCpp: add ':' to arguments regexp"

---

platformio/util.py

fix get_systype() on raspbian

---

platformio/assets/system/99-platformio-udev.rules

add LuatOS ESP32-C3 Development Board

---

.github/workflows/core.yml
platformio/commands/settings.py
platformio/package/commands/uninstall.py
platformio/package/commands/update.py
platformio/platform/factory.py
platformio/project/config.py
platformio/project/helpers.py
platformio/project/integration/tpls/netbeans/nbproject/private/launcher.properties.tpl
platformio/util.py
tests/commands/pkg/test_install.py
tests/package/test_manager.py

https://github.com/codespell-project/codespell

Fix typos discovered by codespell
